### ISSUE TITLE
Lokale bibliotheek

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/respec#6]
In de documentatie staat dit. Maar de lokale bibliotheek is nergens toe te voegen

>Bibliografie
>
>Een bibliografie wordt automatisch toegevoegd, als je termen citeert. Via [SpecRef](https://www.specref.org/) kun je webnormen >opzoeken en citeren als [[citeersleutel]]. Is de bron hierin niet te vinden? Stel dan de bibliografie samen door in metadata.js onder l>ocalBiblio de bronnen toe te voegen, volgens [een specifiek formaat](https://respec.org/docs/#localBiblio).

**Comment by redmer** [comment]
Het komt naast de andere configuratieoptie van ReSpec, zoals hieronder.

```js
var respecConfig = { 
  shortName: "imbor/conceptueel-model",
  localBiblio: {
    nen2660: {
      "title": "NEN 2660-2: Regels voor informatiemodellering van de gebouwde omgeving", 
      ...
    }
  },
  ...
```

Is dat duidelijker?

**Comment by RiX012** [comment]
Ik dacht al dat het zo moest. Maar dan is het dus niet in `metadata.js`, maar in `config.js`. 
Plus als ik dat doe wordt het nergens gerenderd...

**Comment by redmer** [comment]
In https://github.com/Stichting-CROW/respec/wiki/Secties,-index,-appendix,-bibliografie#bibliografie heb ik bovenstaande voorbeelden toegevoegd. Is dat duidelijker?

**Comment by RiX012** [comment]
Zeker!
